name: Deploy BFF

on:
  push:
    branches:
      - main
    paths:
      - 'packages/bff/**'
      - 'packages/shared/**'

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node.js (latest version)
        uses: actions/setup-node@v2

      - name: Audit
        run: yarn audit

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node.js (latest version)
        uses: actions/setup-node@v2

      - name: Build
        run: yarn workspaces run build

  deploy:
    name: Deploy
    needs: [qa, build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: echo "Deployed"
